---
title: "ND Christmas Card"
author: "Tony Galvan"
date: "2023-10-10"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(imager)
library(camcorder)
library(ggtext)
library(showtext)

# Font selected from http://fonts.google.com
tt_family <- "garamond"
font_add_google("Cormorant Garamond", tt_family)

theme_set(theme_minimal())

font_add(family = "fa-brands", regular = "~/Library/Fonts/Font Awesome 6 Brands-Regular-400.otf")
font_add(family = "fa-solid", regular = "~/Library/Fonts/Font Awesome 6 Free-Solid-900.otf")
showtext_auto()

tt_source <- "https://admissions.nd.edu/assets/301960/img_3986_1.jpg"
txt_color = "white"
bg_color <- "#0C2340"
gold <- "#C99700"
green <- "#00843D"

tt_caption <- paste0("Created in R by: Tony Galvan (Class of 2019)  |  Image Source: ", tt_source)

```

## Load the image

Load the image 

```{r LoadImage}

im <- load.image(tt_source)
plot(im)

```

## Start recording

Use the {camcorder} package to record all plots that are output to the console

```{r camcorder}

# start recording
gg_record(
  dir = "~/Downloads/camcorder/2023_ND_Christmas_Card", # where to save the recording
  device = "png", # device to use to save images
  width = 12, # width of saved image
  height = 8, # height of saved image
  units = "in", # units for width and height
  dpi = 300 # dpi to use when saving image
)

```

## Original Image

```{r}

plot(im)

```

## Blurred Image

```{r BlurImage}

im.blurry <- isoblur(im, 2) #Blurry Dome!
plot(im.blurry)

```

## Transform Image Data

```{r TransformData}

R <- im[ , , 1, 1]
B <- im[ , , 1, 2]
G <- im[ , , 1, 3]

df_R <- as.data.frame(R) |>
  mutate(row_id = row_number()) |>
  pivot_longer(
    cols = -row_id, 
    names_to = "col_id", 
    values_to = "red"
  ) |>
  mutate(col_id = parse_number(col_id))

df_B <- as.data.frame(B) |>
  mutate(row_id = row_number()) |>
  pivot_longer(
    cols = -row_id, 
    names_to = "col_id", 
    values_to = "blue"
  ) |>
  mutate(col_id = parse_number(col_id))

df_G <- as.data.frame(G) |>
  mutate(row_id = row_number()) |>
  pivot_longer(
    cols = -row_id, 
    names_to = "col_id", 
    values_to = "green"
  ) |>
  mutate(col_id = parse_number(col_id))

df_image <- df_R |>
  inner_join(df_B, by = c("row_id", "col_id")) |>
  inner_join(df_G, by = c("row_id", "col_id")) |>
  mutate(col_id = 401 - col_id)

```

```{r CreatePlot}

card1 <- df_image |>
  ggplot(aes(row_id, col_id)) +
  geom_point(
    aes(color = red),
    size = 0.25
  ) +
  geom_contour(
    aes(z = green),
    bins = 4,
    linewidth = 0.1,
    color = txt_color
  ) +
  annotate(
    x = 145,
    y = 350,
    geom = "text",
    label = "Merry",
    color = txt_color,
    size = 96,
    fontface = "bold",
    family = tt_family
  ) +
  annotate(
    x = 405,
    y = 350,
    geom = "text",
    label = "Christmas",
    color = txt_color,
    size = 96,
    fontface = "bold",
    family = tt_family
  ) +
  annotate(
    x = 410,
    y = 310,
    geom = "text",
    label = "From: ND Data Science",
    color = txt_color,
    size = 38,
    fontface = "bold",
    family = tt_family
  ) +
  annotate(
    x = 300,
    y = 10,
    geom = "text",
    label = tt_caption,
    color = bg_color,
    size = 12,
    family = tt_family
  ) +
  scale_color_viridis_c(
    option = "cividis"
  ) +
  coord_equal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"
  )

o_alpha <- 0.6

card2 <- card1 +
  annotate(
    x = 521,
    y = 102,
    geom = "point",
    color = "#E84855",
    size = 3.5,
    alpha = o_alpha
  ) +
  annotate(
    x = 466,
    y = 147,
    geom = "point",
    color = "#17BEBB",
    size = 3,
    alpha = o_alpha
  ) +
  annotate(
    x = 491,
    y = 155,
    geom = "point",
    color = "#57AE3E",
    size = 3,
    alpha = o_alpha
  ) +
  annotate(
    x = 466,
    y = 280,
    geom = "point",
    color = "#EA7AF4",
    size = 2.25,
    alpha = o_alpha
  ) +
  annotate(
    x = 490,
    y = 252,
    geom = "point",
    color = "#E84855",
    size = 2.25,
    alpha = o_alpha
  ) +
  annotate(
    x = 480,
    y = 265,
    geom = "point",
    color = "#17BEBB",
    size = 2.25,
    alpha = o_alpha
  ) +
  annotate(
    x = 464,
    y = 248,
    geom = "point",
    color = "#57AE3E",
    size = 2.25,
    alpha = o_alpha
  ) +
  annotate(
    x = 490,
    y = 225,
    geom = "point",
    color = "#EA7AF4",
    size = 2.5,
    alpha = o_alpha
  ) +
  annotate(
    x = 462,
    y = 230,
    geom = "point",
    color = "#FCE84A",
    size = 2.5,
    alpha = o_alpha
  ) +
  annotate(
    x = 490,
    y = 102,
    geom = "point",
    color = "#FCE84A",
    size = 3.5,
    alpha = o_alpha
  ) +
  annotate(
    x = 445,
    y = 118,
    geom = "point",
    color = "#EA7AF4",
    size = 3.5,
    alpha = o_alpha
  ) +
  annotate(
    x = 464,
    y = 169,
    geom = "point",
    color = "#E84855",
    size = 3,
    alpha = o_alpha
  ) +
  annotate(
    x = 455,
    y = 80,
    geom = "point",
    color = "#57AE3E",
    size = 4.25,
    alpha = o_alpha
  ) +
  annotate(
    x = 510,
    y = 178,
    geom = "point",
    color = "#FCE84A",
    size = 3,
    alpha = o_alpha
  ) +
  annotate(
    x = 531,
    y = 67,
    geom = "point",
    color = "#17BEBB",
    size = 4.25,
    alpha = o_alpha
  ) +
  annotate(
    x = 498,
    y = 202,
    geom = "point",
    color = "#57AE3E",
    size = 2.5,
    alpha = o_alpha
  ) +
  annotate(
    x = 478,
    y = 212,
    geom = "point",
    color = "#17BEBB",
    size = 2.5,
    alpha = o_alpha
  ) +
  annotate(
    x = 505,
    y = 110,
    geom = "point",
    color = "#EA7AF4",
    size = 3.75,
    alpha = o_alpha
  ) +
  annotate(
    x = 505,
    y = 140,
    geom = "point",
    color = "#FCE84A",
    size = 3,
    alpha = o_alpha
  ) +
  annotate(
    x = 480,
    y = 74,
    geom = "point",
    color = "#E84855",
    size = 4.25,
    alpha = o_alpha
  )

card2

```

# Save Image

Save your image for sharing. 

```{r}

# This will save your most recent plot
ggsave(
  filename = "2023_ND_Christmas_Card.png",
  device = "png")

gg_stop_recording()

gg_playback(
  name = "2023_ND_Christmas_Card.gif",
  first_image_duration = 5,
  last_image_duration = 5,
  frame_duration = 0.5
)

```

