---
title: "TidyTuesday 2022-01-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gtrendsR)
library(ggtext)

theme_set(theme_light(base_family = "Avenir Next"))
```

```{r load}
res_stocks <- gtrends(keyword = "stock market", geo = "US", time = "2018-01-01 2021-12-31")
res_acorns <- gtrends(keyword = "acorns", geo = "US", time = "2018-01-01 2021-12-31")
```


```{r wrangle}
iot <- res_stocks$interest_over_time %>%
  select(date, stocks = hits) %>%
  left_join(res_acorns$interest_over_time %>%
              select(date, acorns = hits), by = "date")

scale_factor <- mean(res_stocks$interest_over_time$hits) / mean(res_acorns$interest_over_time$hits)
```


```{r visualize}
iot %>%
  ggplot(aes(x = date)) +
  geom_smooth(aes(y = acorns), method = "loess", se = FALSE, color = "#74c947") +
  geom_smooth(aes(y = stocks / scale_factor), method = "loess", se = FALSE, color = "#9471f6") +
  scale_y_continuous(name = "Acorns", sec.axis = sec_axis(~.*scale_factor, name = "Stock Market")) +
  #theme_light() +
  theme(
    axis.title.y.left=element_text(color="#74c947"),
    axis.text.y.left=element_text(color="#74c947"),
    axis.title.y.right=element_text(color="#9471f6"),
    axis.text.y.right=element_text(color="#9471f6"),
    plot.title = element_markdown()
  ) +
  #ggthemes::theme_clean(base_size = 14, base_family = "Avenir Next") +
  labs(x = "",
       title = "Google Trends (2018 - 2021): <span style = 'color:#74c947;'><b>Acorns</b></span> vs. <span style = 'color:#9471f6;'><b>Stock Market</b></span>",
       subtitle = "Web searches peak for both around mid-2020",
       caption = "Source: Google Trends  |  Analysis: Tony Galvan (agalvan@acorns.com)")
```


# Save Image

Save your image for sharing. Be sure to use the `#TidyTuesday` hashtag in your post on twitter! 

```{r}

# This will save your most recent plot
ggsave(
  filename = "2022_01_04_tidy_tuesday.png",
  device = "png")

```


