---
title: "ND Christmas Card"
author: "Tony Galvan"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(imager)
library(camcorder)
library(ggtext)
library(showtext)

# Font selected from http://fonts.google.com
tt_family <- "garamond"
font_add_google("Cormorant Garamond", tt_family)

theme_set(theme_minimal())

font_add(family = "fa-brands", regular = "~/Library/Fonts/Font Awesome 6 Brands-Regular-400.otf")
font_add(family = "fa-solid", regular = "~/Library/Fonts/Font Awesome 6 Free-Solid-900.otf")
showtext_auto()

tt_source <- "~/Downloads/IMG_2008.jpg"
txt_color = "white"
bg_color <- "#0C2340"
blue <- "#0C2340"
gold <- "#ae9142"
green <- "#0a843d"
med_blue <- "#143865"
light_blue <- "#1c4f8f"
dark_gold <- "#8c7535"
light_gold <- "#d39f10"
light_green <- "#b3dac5"
sky_blue <- "#e1e8f2"
sky_blue_dark <- "#c1cddd"
sky_blue_light <- "#edf2f9"
warm_white <- "#f8f4ec"
warm_white_dark <- "#efe9d9"

all_nd_colors <- c(
  blue, gold, green, med_blue, light_blue, dark_gold, light_gold, light_green, sky_blue, sky_blue_dark, sky_blue_light, warm_white, warm_white_dark
)

tt_caption <- paste0("Created in R by: Tony Galvan (Class of 2019)  |  Image Source: ", tt_source)

```

## Load the image

Load the image 

```{r LoadImage}

im_original <- load.image(tt_source)

```

## Start recording

Use the {camcorder} package to record all plots that are output to the console

```{r camcorder}

# start recording
gg_record(
  dir = "~/Downloads/camcorder/2024_ND_Christmas_Card", # where to save the recording
  device = "png", # device to use to save images
  width = 12, # width of saved image
  height = 8, # height of saved image
  units = "in", # units for width and height
  dpi = 300 # dpi to use when saving image
)

```

## Resize Image

```{r ResizeImage}
# get the dimensions of the image
dim(im_original)

# resize the image with original aspect ratio to a width of 600 pixels
im_small <- resize(
  im_original, 
  600, 
  dim(im_original)[2] * 600 / dim(im_original)[1]
)

# get the dimensions of the image
dim(im_small)

# using the imsub function from the imager package, crop the image and keep only the top portion with a height of 400 pixels
im <- imsub(im_small, y < 401)

# get the dimensions of the image
dim(im)

```

## Original Image

```{r}

plot(im)

```

## Blurred Image

```{r BlurImage}

im.blurry <- isoblur(im, 2) #Blurry Grotto!
plot(im.blurry)

```

## Transform Image Data

```{r TransformData}

R <- im[ , , 1, 1]
B <- im[ , , 1, 2]
G <- im[ , , 1, 3]

df_R <- as.data.frame(R) |>
  mutate(row_id = row_number()) |>
  pivot_longer(
    cols = -row_id, 
    names_to = "col_id", 
    values_to = "red"
  ) |>
  mutate(col_id = parse_number(col_id))

df_B <- as.data.frame(B) |>
  mutate(row_id = row_number()) |>
  pivot_longer(
    cols = -row_id, 
    names_to = "col_id", 
    values_to = "blue"
  ) |>
  mutate(col_id = parse_number(col_id))

df_G <- as.data.frame(G) |>
  mutate(row_id = row_number()) |>
  pivot_longer(
    cols = -row_id, 
    names_to = "col_id", 
    values_to = "green"
  ) |>
  mutate(col_id = parse_number(col_id))

df_image <- df_R |>
  inner_join(df_B, by = c("row_id", "col_id")) |>
  inner_join(df_G, by = c("row_id", "col_id")) |>
  mutate(col_id = max(col_id) + 1 - col_id)

```

```{r CreatePlot}

# create a dataframe of all the possible options for geom_point_color, geom_contour_color, and scale_color_viridis_c_option
df_options <- expand.grid(
  geom_point_color = c("red", "green", "blue"),
  geom_contour_color = c("red", "green", "blue"),
  scale_color_viridis_c_option = c("A", "B", "C", "D", "E", "F", "G", "H")
)

i <- 61
df_image |>
  ggplot(aes(row_id, col_id)) +
  geom_point(
    aes(
      color = !!sym(as.character(df_options$geom_point_color[i]))
    ),
    size = 0.25
  ) +
  geom_contour(
    aes(z = !!sym(as.character(df_options$geom_contour_color[i]))),
    bins = 4,
    linewidth = 0.1,
    color = txt_color
  ) +
  scale_color_viridis_c(
    option = as.character(df_options$scale_color_viridis_c_option[i])
  ) +
  coord_equal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"
  )

```


```{r ReColorImage}

# randomly create a color palette of ND colors
nd_pal <- sample(all_nd_colors, sample(2:length(all_nd_colors), 1))

df_image |>
  ggplot(aes(row_id, col_id)) +
  geom_point(
    aes(
      color = red
    ),
    size = 0.25
  ) +
  geom_contour(
    aes(z = blue),
    bins = 4,
    linewidth = 0.1,
    color = txt_color
  ) +
  scale_color_gradientn(
    # colors = c(gold, green)
    # colors = c(green, gold)
    # colors = c(blue, gold)
    # colors = c(blue, gold, green)
    # colors = c(blue, "#143865", "#1c4f8f", green, "#8c7535", gold, "#d39f10")
    # colors = c(blue, "#143865", "#1c4f8f", "#8c7535", gold, "#d39f10")
    # colors = c("#0a843d", "#efe9d9", "#edf2f9", "#b3dac5") # nice green and cream
    # colors = c("#0C2340","#d39f10") # blue and gold
    colors = c("#143865", "#8c7535", "#e1e8f2", "#edf2f9") # blue, gold, and cream
    # colors = nd_pal
  ) +
  coord_equal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"
  )

```


# Save Image

Save your image for sharing. 

```{r}

# This will save your most recent plot
ggsave(
  filename = "2024_ND_Christmas_Card.png",
  device = "png")

gg_stop_recording()

gg_playback(
  name = "2024_ND_Christmas_Card.gif",
  first_image_duration = 5,
  last_image_duration = 5,
  frame_duration = 0.5
)

```

