---
title: "plastic pollution"
author: "Tony Galvan"
date: "1/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
theme_set(theme_light())
```

## R Markdown

```{r}
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')
```

```{r}
plastics %>%
  count(year)
```

```{r}
plastics %>%
  count(country, sort = TRUE)
```

```{r}
plastics %>%
  count(parent_company, sort = TRUE)
```

```{r}
blacklist <- c("Unbranded", "null", "Grand Total", "NULL", "Assorted")

top_pollution_companies <- plastics %>%
  filter(!parent_company %in% blacklist) %>%
  count(parent_company, wt = grand_total, name = "company_total", sort = TRUE) %>%
  top_n(10)
```


```{r}
plastics %>%
  inner_join(top_pollution_companies, by = "parent_company") %>%
  count(parent_company, year, company_total, wt = grand_total, name = "year_total", sort = TRUE) %>%
  mutate(parent_company = fct_reorder(parent_company, company_total)) %>%
  ggplot(aes(year_total, parent_company, fill = factor(year))) +
  geom_col() +
  scale_x_continuous(labels = scales::comma_format()) +
  scale_fill_manual(values = c("#629677","#485665")) +
  theme(legend.position = "bottom") +
  labs(x = "Plastic pollution count (all types)",
    y = "",
    fill = "Year",
    title = "Plastic Pollution: 2019 & 2020",
    subtitle = "Top 10 companies with the most plastic pollution",
    caption = "Source: https://www.breakfreefromplastic.org/  |  Analysis: Tony Galvan (@GDataScience1)")
```

```{r}
# This will save your most recent plot
ggsave(
  filename = "gdatascience1_202105.png",
  device = "png",
  width = 5.5)

```